### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'video.expo.local.key'

### ISSUE THREAD

**Issue by MarconGit** [gschomburg/secure_spacebrewSamples#1]
Hi,

Thank you for porting SpaceBrew to WSS! It could save a project where I need access to senors on a mobile. I tried to run the secure server on MacOS 10.15.1 but I get the following error:

---
```
 % node node_server.js --secure        

Running Spacebrew, start with argument '--help' to see available configuration arguments.
More info at http://www.spacebrew.cc

internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'video.expo.local.key'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.spacebrew.createServer (/Users/xxx/Downloads/spacebrew-sec/spacebrew.js:67:21)
    at main (/Users/xxx/Downloads/spacebrew-sec/node_server.js:199:13)
    at Object.<anonymous> (/Users/xxx/Downloads/spacebrew-sec/node_server.js:207:1)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'video.expo.local.key'
}
```
---

Do you have an idea what could be wrong?

**Comment by MarconGit** [comment]
Ok, I got past that one. The names and paths to the certs were wrong in spacebrew.js' spacebrew.createServer. Replacing 
`var key =  ...
var cert =  ...`

with

`var key = './secure/key.pem';
var cert = './secure/cert.pem';`

gets me one step further. Now I get the following error:

`% node node_server.js --secure

Running Spacebrew, start with argument '--help' to see available configuration arguments.
More info at http://www.spacebrew.cc

fs.js:143
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:143:11)
    at Object.mkdir (fs.js:810:14)
    at setupLogDirectory (/Users/xxx/Downloads/spacebrew-sec/spacebrew_live_persist.js:77:7)
    at Object.livePersister.persistRoutes (/Users/xxx/Downloads/spacebrew-sec/spacebrew_live_persist.js:492:2)
    at main (/Users/xxx/Downloads/spacebrew-sec/node_server.js:200:26)
    at Object.<anonymous> (/Users/xxx/Downloads/spacebrew-sec/node_server.js:207:1)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14) {
  code: 'ERR_INVALID_CALLBACK'
}
`
